apiVersion: apps/v1
kind: Deployment
metadata:
  name: coastalseven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coastal-api
  template:
    metadata:
      labels:
        app: coastal-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: fastapi-container
        image: coastalseven-day6:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        # EMAIL SETTINGS (Extracted from your config.py)
        - name: SMTP_USER
          value: "phanimahankali23@gmail.com"
        - name: SMTP_PASSWORD
          value: "your_app_password"  # Update this to your real password
        - name: EMAILS_FROM_EMAIL
          value: "phanimahankali23@gmail.com"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "465"
        - name: EMAILS_FROM_NAME
          value: "Portfolio Contact"
        # DATABASE SETTINGS
        - name: POSTGRES_SERVER
          value: "db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "Bhaskar_6281"
        - name: POSTGRES_DB
          value: "sepnoty_db"