apiVersion: apps/v1
kind: Deployment
metadata:
  name: coastalseven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coastal-api
  template:
    metadata:
      labels:
        app: coastal-api
    spec:
      containers:
      - name: fastapi-container
        # Use simple name, no username prefix
        image: coastalseven-day6:latest 
        # IMPORTANT: 'Never' forces K8s to look for the image locally 
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8000
        env:
        - name: MAIL_FROM
          value: "admin@example.com"
        - name: MAIL_USERNAME
          value: "admin"
        - name: MAIL_PASSWORD
          value: "password"
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_SERVER
          value: "smtp.gmail.com"
        - name: MAIL_FROM_NAME
          value: "Coastalseven Admin"